- name: Hello World Sample
  hosts: all
  become: true
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: uninstall nginx ec2
      apt:
       shell: apt remove nginx -y      
    - name: install apache2 ec2
      apt:
       shell: apt install apache2 -y
#        name="nginx"
#        state=present 
#        update_cache=true
