- name: Hello World Sample
  hosts: all
  become: true
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
        
    - name: install nginx ec2
      apt:
       name="nginx"
       state=present 
       update_cache=true
